language: python
python:
  - 3.8
sudo: false
cache:
  pip: true
  directories:
    - $HOME/.npm
before_install:
  - pip install -U pip setuptools
  - nvm install 6
script:
  - pip install jupyterlab
  - jupyter labextension install DavidZhang73/jupyterlab-atom-one-dark-theme
  - jupyter labextension list 2>&1 | grep -q jupyterlab-atom-one-dark-theme
